- name: Set the system timezone
  hosts: web_servers
  become: true
  gather_facts: false

  vars_files:
    - /ansible/vars/vars.yml

  tasks:
    - name: Set timezone to America/Chicago
      timezone:
        name: "{{ timezone }}"
