- name: Update Packages
  import_playbook: update-packages.yml

- name: Install Docker
  import_playbook: install-docker.yml

# - name: Install Elastic Agent
#   import_playbook: install-elastic-agent.yml