- name: Deploy web application
  hosts: web_servers
  become: true
  gather_facts: false

  vars_files:
    - /ansible/vars/vars.yml
    - /ansible/vars/encrypted_vars.yml

  tasks:
    - name: Clone production repository
      git:
        repo: https://github.com/elblayko/blakerenton.net-app.git
        dest: /usr/local/share/blakerenton-net

    - name: Create acme.json and set permissions
      become: true
      file:
        path: /usr/local/share/blakerenton-net/traefik/acme.json
        state: touch
        mode: 0600
        access_time: preserve
        modification_time: preserve

    - name: Create .env and set permissions
      file:
        path: /usr/local/share/blakerenton-net/traefik/.env
        state: touch
        mode: 0600
        access_time: preserve
        modification_time: preserve

    - name: Add CloudFlare API e-mail to .env
      lineinfile:
        path: /usr/local/share/blakerenton-net/traefik/.env
        line: "CF_API_EMAIL={{ cloudflare_secret.email }}"
        insertafter: EOF

    - name: Add CloudFlare API key to .env
      lineinfile:
        path: /usr/local/share/blakerenton-net/traefik/.env
        line: "CF_API_KEY={{ cloudflare_secret.api_key }}"
        insertafter: EOF

      # Ansible doesn't support Docker Compose > 2.0, use shell instead.
      # Ref: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html

    - name: Start Traefik service
      command: docker compose -f /usr/local/share/blakerenton-net/traefik/docker-compose.yml up -d --force-recreate

    - name: Start LittleLink service
      command: docker compose -f /usr/local/share/blakerenton-net/home/docker-compose.yml up -d --force-recreate
